# Generated by Django 5.2.6 on 2025-09-21 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_userproxy_alter_appsetting_options_and_more'),
        ('app_hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Hồ sơ nhân sự', 'verbose_name_plural': 'Hồ sơ nhân sự'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='app_home.department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='performance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Hiệu suất (0–100)'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='app_home.position', verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='shifts_this_month',
            field=models.PositiveIntegerField(default=0, verbose_name='Số ca trong tháng'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Đang làm'), ('inactive', 'Nghỉ việc'), ('on_leave', 'Đang nghỉ phép')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng giờ làm'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng'),
        ),
    ]
