# Generated by Django 5.2.6 on 2025-09-21 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_userproxy_alter_appsetting_options_and_more'),
        ('app_inventory', '0003_alter_ingredient_options_alter_inventorylot_options_and_more'),
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Món trên menu', 'verbose_name_plural': 'Món trên menu'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Định lượng nguyên liệu', 'verbose_name_plural': 'Định lượng nguyên liệu'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Còn bán'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='app_home.menucategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Ảnh minh họa'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên món'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='app_inventory.ingredient', verbose_name='Nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='app_menu.menuitem', verbose_name='Món'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Định lượng/1 phần'),
        ),
    ]
