# Generated by Django 5.2.6 on 2025-09-21 09:39

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Danh sách nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='appsetting',
            options={'verbose_name': 'Thiết lập ứng dụng', 'verbose_name_plural': 'Thiết lập ứng dụng'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='diningtable',
            options={'verbose_name': 'Bàn ăn', 'verbose_name_plural': 'Bàn ăn'},
        ),
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name': 'Danh mục nguyên liệu', 'verbose_name_plural': 'Danh mục nguyên liệu'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Danh mục menu', 'verbose_name_plural': 'Danh mục menu'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Chức danh', 'verbose_name_plural': 'Chức danh'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Đơn vị đo', 'verbose_name_plural': 'Đơn vị đo'},
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='currency',
            field=models.CharField(default='VND', max_length=10, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT mặc định (%)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên phòng ban'),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên bàn'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự sắp xếp'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='app_home.department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên chức danh'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã đơn vị'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên đơn vị'),
        ),
    ]
