# Generated by Django 5.2.6 on 2025-09-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_userproxy_alter_appsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Đơn vị đo hehe', 'verbose_name_plural': 'Đơn vị đo hehe'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã đơn vị hehee'),
        ),
    ]
