version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: foodshopeight:web
    container_name: foodshop_web
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: web
      # Nếu DB ngoài, có thể set WAIT_FOR_HOST/PORT để chờ DB sẵn sàng
      # WAIT_FOR_HOST: your-db-host
      # WAIT_FOR_PORT: "5432"
    volumes:
      - static_volume:/app/static_root
      - media_volume:/app/media
    depends_on:
      - redis
    networks: [foodnet]

  worker:
    image: foodshopeight:web
    container_name: foodshop_worker
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: worker
    depends_on:
      - redis
    networks: [foodnet]
    restart: unless-stopped

  beat:
    image: foodshopeight:web
    container_name: foodshop_beat
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: beat
    depends_on:
      - redis
    networks: [foodnet]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: foodshop_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks: [foodnet]
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: foodshop_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks: [foodnet]
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  foodnet:
    driver: bridge
