# Generated by Django 5.2.6 on 2025-09-21 09:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_userproxy_alter_appsetting_options_and_more'),
        ('app_menu', '0002_alter_menuitem_options_alter_recipeitem_options_and_more'),
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Mặt hàng trong đơn', 'verbose_name_plural': 'Mặt hàng trong đơn'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn tất'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên khách'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SĐT khách'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('preparing', 'Đang làm'), ('ready', 'Sẵn sàng'), ('completed', 'Hoàn tất'), ('cancelled', 'Hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Ăn tại chỗ'), ('takeaway', 'Mang đi'), ('delivery', 'Giao hàng')], default='dine_in', max_length=20, verbose_name='Hình thức'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Hoàn tiền')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app_home.diningtable', verbose_name='Bàn'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app_menu.menuitem', verbose_name='Món'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên món (snapshot)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_order.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thành tiền (dòng)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá (snapshot)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('ewallet', 'Ví điện tử')], max_length=20, verbose_name='Phương thức'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_order.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm thanh toán'),
        ),
    ]
