# Generated by Django 5.2.6 on 2025-09-04 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylot',
            name='quantity_remaining',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
