# Generated by Django 5.2.6 on 2025-09-21 09:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_userproxy_alter_appsetting_options_and_more'),
        ('app_inventory', '0002_alter_inventorylot_quantity_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Nguyên liệu', 'verbose_name_plural': 'Nguyên liệu'},
        ),
        migrations.AlterModelOptions(
            name='inventorylot',
            options={'verbose_name': 'Lô nhập kho', 'verbose_name_plural': 'Lô nhập kho'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='app_home.ingredientcategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='max_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tồn tối đa'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tồn tối thiểu'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá tham chiếu/đơn vị'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('in_stock', 'Đủ hàng'), ('low_stock', 'Gần hết'), ('out_of_stock', 'Hết hàng')], default='in_stock', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='app_home.unit', verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn dùng'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='app_inventory.ingredient', verbose_name='Nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng nhập'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='quantity_remaining',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng còn lại'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='app_inventory.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='inventorylot',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Người liên hệ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Số điện thoại'),
        ),
    ]
